[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
formatted-index-macro = { path = "crates/formatted-index-macro", version = "1.0.0" }

[profile.release]
codegen-units = 1
lto = true
